# Generated by Django 2.0.3 on 2018-04-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demo', '0002_auto_20180405_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.CharField(max_length=20)),
            ],
        ),
    ]
