# Generated by Django 2.0.3 on 2018-04-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_hotelview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelView',
        ),
    ]
